#!/bin/bash

## Configuration, will be overridden by config file
	
# Notification title when a screenshot is saved to disk, or copied to clipboard
succ_noTit="Kasha!"

# Notification text when a screenshot is captured, and saved to disk
succ_noTex="Screenshot saved!"

# Notification text when a screenshot is captured, and copied to clipboard
succ_noTex_cp="Screenshot copied to clipboard!"

# Notification title when a QR Code is scanned and copied to clipboard
succ_noTit_sccop="QR Code scan result"

# Prompt dialog title when qr code scanned
dia_tit="Prompt"

# Prompt dialog text when qr code scanned
dia_tex="QR Code detected, and sucessfully scanned.\n Do you want to copy the scan result instead?"

# Prompt dialog copy image button
dia_imgcop_butt="Copy image"

# Prompt dialog copy scan result button
dia_sccop_butt="Copy scan result"

# Screenshot save dir
sv_dir="/home/$USER/Pictures/"

# Screenshot file name
sv_name="$(date)"

## Overriding Config file (will auto make them)

	con_dir=/home/$USER/.config/eses-beta
	con_file=/home/$USER/.config/eses-beta/config

	if [ -d "$con_dir" ]; then
		test -f "$con_file" || sed -n "5, 33p" eses-beta > $con_file
	else
		mkdir $con_dir
		sed -n "5, 33p" eses-beta > $con_file
	fi

	source $con_file

## Making sure save directory is exist

	test -d "$sv_dir" || mkdir $sv_dir

## Display server checker

	whatDis=0;
	
	if [ $XDG_SESSION_TYPE == 'wayland' ]; then
		whatDis=0;
	else
		whatDis=1;
	fi

	# it will be 0 if wayland and 1 if X11	

## Code

function printHelp {
printf 'Usage: eses-beta [OPTION]
Screenshot script with QR Scanner feature
	 
There are four modes, selectable by the below options:
  --select        Screenshot selected area / selected window, and save it as a file
  --whole         Screenshot whole screen and save it as a file in your desired folder
  --whole_cp      Screenshot whole screen and put it on clipboard without saving
  --select_cp     Screenshot selected area / selected window, and put it on clipboard, then run QR code magic.

    Also try looking at "man eses" for more documentation.
'
}


if [ $whatDis = "0" ]; then
	case "$1" in
		--help)
			printHelp
			echo "    eses is currently running in Wayland mode."
			;;
		--select)
			grim -g "$(slurp)" "$sv_dir$sv_name"
			notify-send -a eses "$succ_noTit" "$succ_noTex"
			;;
		--whole)
			grim "$sv_dir$sv_name"
			notify-send -a eses "$succ_noTit" "$succ_noTex"
			;;
		--whole_cp)
			grim - | wl-copy -t image/png
			notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
			;;
		--select_cp)
			tmp_file="/tmp/qr.png"

			# maimselect > "$tmp_file"
			grim -g "$(slurp)" "$tmp_file"
			scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

			if [ -z "$scanresult" ]; then
				wl-copy -t image/png < $tmp_file
				notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
			else
				ask=$(zenity --question --text="$dia_tex" --title="$dia_tit" --icon-name=info \
				--no-wrap --ok-label="$dia_sccop_butt" --cancel-label="$dia_imgcop_butt" --ellipsize)

				if [ $? = "0" ]; then
						echo "$scanresult" | wl-copy
						convert $tmp_file -resize 75x75 "$tmp_file"
						notify-send -a eses -i "$tmp_file" "$succ_noTit_sccop" "$scanresult"
				elif [ $? = "1" ]; then
						wl-copy -t image/png < $tmp_file
						notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
				fi
			fi
			;;
	esac

elif [ $whatDis = "1" ]; then
	case "$1" in
		--help)
			printHelp
			echo '    eses is currently running in Xorg (x11) mode.'
			;;
		--select)
			maim --hidecursor --select "$sv_dir$sv_name"
			notify-send -a eses "$succ_noTit" "$succ_noTex"
			;;
		--whole)
			maim --hidecursor "$sv_dir$sv_name"
			notify-send -a eses "$succ_noTit" "$succ_noTex"
			;;
		--whole_cp)
			maim --hidecursor | xclip -selection clipboard -t image/png
			notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
			;;
		--select_cp)
			tmp_file="/tmp/qr.png"

			# maimselect > "$tmp_file"
			maim --hidecursor --select "$tmp_file"
			scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

			if [ -z "$scanresult" ]; then
				xclip -selection clipboard -t image/png $tmp_file
				notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
			else
				ask=$(zenity --question --text="$dia_tex" --title="$dia_tit" --icon-name=info --no-wrap --ok-label="$dia_sccop_butt" --cancel-label="$dia_imgcop_butt" --ellipsize)
				if [ $? = "0" ]; then
					echo "$scanresult" | xclip -selection clipboard -filter
					convert $tmp_file -resize 75x75 "$tmp_file"
					notify-send -a eses -i "$tmp_file" "$succ_noTit_sccop" "$scanresult"
				elif [ $? = "1" ]; then
					xclip -selection clipboard -t image/png $tmp_file
					notify-send -a eses "$succ_noTit" "$succ_noTex_cp"
				fi
			fi
			;;
	esac
fi
