#!/bin/bash

## Configuration, will be overrided by config file
	
# Notification title when maim --hidecursor successfully saved
succ_noTit="Kasha!"

# Notification text when maim --hidecursor successfully saved
succ_noTex="Screenshot saved!"

# Notification text when maim --hidecursor successfully saved
succ_noTex_cp="Screenshot copied to clipboard!"

# Notification title when QR Scanned and copied
succ_noTit_sccop="QR Code scan result"

# Prompt dialog title when qr code scanned
dia_tit="Prompt"

# Prompt dialog text when qr code scanned
dia_tex="QR Code detected, and sucessfully scanned\n Do you want to copy the scan result instead?"

# Prompt dialog copy image button
dia_imgcop_butt="Copy image"

# Prompt dialog copy image button
dia_sccop_butt="Copy scan result"

# maim --hidecursor save dir
sv_dir="/home/$USER/Pictures/"

# maim --hidecursor file name
sv_name="$(date)"

## Overriding Config file (will auto make them)

	con_dir=/home/$USER/.config/eses-beta
	con_file=/home/$USER/.config/eses-beta/config

	if [ -d "$con_dir" ]; then
		test -f "$con_file" || sed -n "5, 33p" eses-beta > $con_file
	else
		mkdir $con_dir
		sed -n "5, 33p" eses-beta > $con_file
	fi

	source $con_file

## Making sure save directory is exist

	test -d "$sv_dir" || mkdir $sv_dir

## Display server checker

	whatDis=0;
	
	if [ $XDG_SESSION_TYPE == 'wayland' ]; then
		whatDis=0;
	else
		whatDis=1;
	fi

	# it will be 0 if wayland and 1 if X11

	# for test purpose, will delete later
	echo $whatDis
	

## Code

if [ $whatDis = "0" ]; then
	case "$1" in
		--select)
  			grim -g "$(slurp)" "$sv_dir$sv_name"
  			notify-send -t 1000 "$succ_noTit" "$succ_noTex"
  			;;
 		--whole)
  			grim "$sv_dir$sv_name"
  			notify-send -t 1000 "$succ_noTit" "$succ_noTex"
  			;;
 		--whole_cp)
  			grim - | wl-copy -t image/png
  			notify-send -t 1000 "$succ_noTit" "$succ_noTex_cp"
  			;;
 		--select_cp)
  			tmp_file="/tmp/qr.png"

  			# maimselect > "$tmp_file"
  			grim -g "$(slurp)" "$tmp_file"
  			scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

  			if [ -z "$scanresult" ]; then
   				wl-copy -t image/png < $tmp_file
   				notify-send "$succ_noTit" "$succ_noTex_cp"
  			else
   				ask=$(zenity --question --text="$dia_tex" --title="$dia_tit" --icon-name=info --no-wrap --ok-label="$dia_sccop_butt" --cancel-label="$dia_imgcop_butt" --ellipsize)
   				if [ $? = "0" ]; then
    					echo "$scanresult" | wl-copy
    					convert $tmp_file -resize 75x75 "$tmp_file"
    					notify-send -i "$tmp_file" "$succ_noTit_sccop" "$scanresult"
   				elif [ $? = "1" ]; then
    					wl-copy -t image/png < $tmp_file
    					notify-send -t 1000 "$succ_noTit" "$succ_noTex_cp"
   				fi
  			fi
  			;;
	esac

elif [ $whatDis = "1" ]; then
	case "$1" in
		--select)
			maim --hidecursor --select "$sv_dir$sv_name"
			notify-send "$succ_noTit" "$succ_noTex"
			;;
		--whole)
			maim --hidecursor "$sv_dir$sv_name"
			notify-send "$succ_noTit" "$succ_noTex"
			;;
		--whole_cp)
			maim --hidecursor | xclip -selection clipboard -t image/png
			notify-send "$succ_noTit" "$succ_noTex_cp"
			;;
		--select_cp)
			tmp_file="/tmp/qr.png"

			# maimselect > "$tmp_file"
			maim --hidecursor --select "$tmp_file"
			scanresult=$(zbarimg --quiet --raw "$tmp_file" | tr -d '\n')

			if [ -z "$scanresult" ]; then
				xclip -selection clipboard -t image/png $tmp_file
				notify-send "$succ_noTit" "$succ_noTex_cp"
			else
				ask=$(zenity --question --text="$dia_tex" --title="$dia_tit" --icon-name=info --no-wrap --ok-label="$dia_sccop_butt" --cancel-label="$dia_imgcop_butt" --ellipsize)
				if [ $? = "0" ]; then
					echo "$scanresult" | xclip -selection clipboard -filter
					convert $tmp_file -resize 75x75 "$tmp_file"
					notify-send -i "$tmp_file" "$succ_noTit_sccop" "$scanresult"
				elif [ $? = "1" ]; then
					xclip -selection clipboard -t image/png $tmp_file
					notify-send "$succ_noTit" "$succ_noTex_cp"
				fi
			fi
			;;
	esac
fi
